// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKqGdLdtYgWIrxvpGgTbA_6qfiR2ENE6A',
    appId: '1:564580712528:web:3542ead08ccf02a42d9155',
    messagingSenderId: '564580712528',
    projectId: 'smarthealth-4456d',
    authDomain: 'smarthealth-4456d.firebaseapp.com',
    storageBucket: 'smarthealth-4456d.firebasestorage.app',
    measurementId: 'G-BLHG3VVPQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT6GvLmvqd5fkploMXNXl6U1EOkd0lm3M',
    appId: '1:564580712528:android:4744d12c513942592d9155',
    messagingSenderId: '564580712528',
    projectId: 'smarthealth-4456d',
    storageBucket: 'smarthealth-4456d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Q8bp4lET1QAyJB7MzCplUtuDOi56xpk',
    appId: '1:564580712528:ios:0ee99bbbc9fd1ec82d9155',
    messagingSenderId: '564580712528',
    projectId: 'smarthealth-4456d',
    storageBucket: 'smarthealth-4456d.firebasestorage.app',
    iosBundleId: 'com.sanctuaryhealth.smartHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Q8bp4lET1QAyJB7MzCplUtuDOi56xpk',
    appId: '1:564580712528:ios:0ee99bbbc9fd1ec82d9155',
    messagingSenderId: '564580712528',
    projectId: 'smarthealth-4456d',
    storageBucket: 'smarthealth-4456d.firebasestorage.app',
    iosBundleId: 'com.sanctuaryhealth.smartHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKqGdLdtYgWIrxvpGgTbA_6qfiR2ENE6A',
    appId: '1:564580712528:web:1b0c0c92f34992da2d9155',
    messagingSenderId: '564580712528',
    projectId: 'smarthealth-4456d',
    authDomain: 'smarthealth-4456d.firebaseapp.com',
    storageBucket: 'smarthealth-4456d.firebasestorage.app',
    measurementId: 'G-DM6JNNB1D4',
  );
}
